version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${INSTANCE}-nest-api
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    container_name: postgres${INSTANCE}
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - postgres${INSTANCE}:/var/lib/postgresql/data

volumes:
  postgres${INSTANCE}:
    name: ${INSTANCE}-nest-docker-db